name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
    who-to-greet:  "MY_NAME"
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}

branding:
  icon: "mic"
  color: "purple"
